name: NeteaseCloudMusic

on:
  workflow_dispatch:
  schedule:
  - cron: '0 17 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
        
    - name: Main
      env:
        NETEASE_PHONE: ${{ secrets.NETEASE_PHONE }}
        NETEASE_PASSWORD: ${{ secrets.NETEASE_PASSWORD }}
        BARK: ${{ secrets.BARK_PUSH}}
      working-directory: ./utils/NeteaseCloudMusic
      run: |
        pip install -r requirements.txt
        python index.py
